server:
  port: 7001
eureka:
  instance:
    hostname: aigou_eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/
spring:
  application:
    name: AIGOU_EUREKA